version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: app_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prismacredentials
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
